ProjecVete/urls.py
from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.inicio.urls', 'inicio'), namespace='inicio')),
    path('regMedic/', include(('apps.regmedic.urls', 'regmedic'), namespace='regmedic')),
    path('accounts/', include('apps.registration.urls')),
    path('reporte/', include(('apps.reporte.urls', 'reporte'), namespace='reporte')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),


    path('accounts/', include('apps.registration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

apps/inicio/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from apps.inicio.views import DashboardView, AccesoDene, \
    Manten_Client, Manten_Pets, Manten_Client_edit, Manten_Pets_edit, empleadosList, EmpleadosDelete, NotificationView

urlpatterns = [
    path('', DashboardView.as_view(), name='inicio'),
    path('login/', auth_views.LoginView.as_view(template_name='inicio/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='inicio/login.html'), name='logout'),
    path('AccesoDenegado/', AccesoDene.as_view(), name='accesodene'),
    path('notificaciones/', NotificationView.as_view(), name='noti'),

    # MANTENIMIENTO
    path('Mantenimiento/Clientes', Manten_Client.as_view(), name='man_client'),
    path('Mantenimiento/Clientes/Modificar/<int:pk>/',
         Manten_Client_edit.as_view(), name='man_client_edit'),
    path('Mantenimiento/Mascotas', Manten_Pets.as_view(), name='man_pets'),
    path('Mantenimiento/Mascotas/Modificar/<int:pk>/',
         Manten_Pets_edit.as_view(), name='man_pets_edit'),
    path('Mantenimiento/empleados/', empleadosList.as_view(), name='list_emp'),
    path('Mantenimiento/empleados/delete/<int:pk>/',
         EmpleadosDelete.as_view(), name="del_emp"),

]

apps/regmedic/urls.py
from django.urls import path

from .views import ClienteView, ClienteNuevo, ClienteEdit, ClienteInact, ClienteDetail, MascotaView, MascotaNew, MascotaDetail, MascotaEdit, MascotaInact, ConsultaView, ConsultaNew, ConsultaEdit, ConsultaDel, ConsultaDetail, VacunaView, VacunaNew, VacunaEdit, VacunaDel, DespaView, DespaNew, DespaEdit, DespaDel, ClienteDelete, Mascota_Delete

urlpatterns = [
#URLS CLIENTES
    path('Clientes', ClienteView.as_view(), name='Cliente_list'),
    path('Cliente/new', ClienteNuevo.as_view(), name='Cliente_form'),
    path('Cliente/edit/<int:pk>', ClienteEdit.as_view(), name='Cliente_edit'),
    path('Cliente/inac/<int:id>', ClienteInact, name='Cliente_inac'),
    path('Cliente/detail/<int:pk>', ClienteDetail.as_view(), name='Cliente_detail'),
    path('Cliente/<int:pk>/delete', ClienteDelete.as_view(), name='Cliente_delete'),
#URLS MASCOTAS
    path('Mascotas', MascotaView.as_view(), name='Mascota_list'),
    path('Mascota/new', MascotaNew.as_view(), name='Mascota_form'),
    path('Mascota/detail/<int:pk>', MascotaDetail.as_view(), name='Mascota_detail'),
    path('Mascota/edit/<int:pk>', MascotaEdit.as_view(), name='Mascota_edit'),
    path('Mascota/inac/<int:id>', MascotaInact, name='Mascota_inac'),
    path('Mascota/<int:pk>/delete/', Mascota_Delete.as_view(), name='Mascota_delete'),
#URLS CONSULTAS
    path('Consultas', ConsultaView.as_view(), name='Consulta_list'),
    path('Consulta/new', ConsultaNew.as_view(), name='Consulta_form'),
    path('Consulta/edit/<int:pk>', ConsultaEdit.as_view(), name='Consulta_edit'),
    path('Consulta/eliminar/<int:pk>', ConsultaDel.as_view(), name='Consulta_del'),
    path('Consulta/detail/<int:pk>', ConsultaDetail.as_view(), name='Consulta_detail'),
#URLS VACUNACIONES
    path('Vacunas', VacunaView.as_view(), name='Vacuna_list'),
    path('Vacuna/new', VacunaNew.as_view(), name='Vacuna_form'),
    path('Vacuna/edit/<int:pk>', VacunaEdit.as_view(), name='Vacuna_edit'),
    path('Vacuna/eliminar/<int:pk>', VacunaDel.as_view(), name='Vacuna_del'),
#URLS DESPARASITACIONES
    path('Despa', DespaView.as_view(), name='Despa_list'),
    path('Despa/new', DespaNew.as_view(), name='Despa_form'),
    path('Despa/edit/<int:pk>', DespaEdit.as_view(), name='Despa_edit'),
    path('Despa/eliminar/<int:pk>', DespaDel.as_view(), name='Despa_del'),

]

apps/inicio/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True,null=True)

    class Meta:
        abstract=True

apps/regmedic/models.py
from django.db import models
from datetime import datetime, date, time, timedelta

# Create your models here.

# MODELO CLIENTE
class ModeloBase(models.Model):
    estado = models.BooleanField(default=True)
    estado_notificacion = models.BooleanField(default=True, verbose_name='Estado de Notificación')
    prox_cita = models.DateField(default=date.today, verbose_name='Proxima Visita')
    cont_dias = models.IntegerField(default=3)

    class Meta:
        abstract=True

class Cliente(ModeloBase):
    # Nacionalidad
    nat = "V-"
    juri = "J-"
    ex = "E-"
    tipo_cliente = [(nat, 'V-'), (juri, 'J-'), (ex, 'E-')]

    # Codigo de area Movil
    Digitel1 = "0412"
    Movilnet1 = "0416"
    Movilnet2 = "0426"
    Movistar1 = "0414"
    Movistar2 = "0424"
    cod_movil = [(Digitel1, "0412"), (Movilnet1, "0416"),
                 (Movilnet2, "0426"), (Movistar1, "0414"), (Movistar2, "0424")]

    tipo = models.CharField(max_length=10, choices=tipo_cliente, default=nat)
    cedula = models.CharField(primary_key=True, verbose_name="Número de Cédula", max_length=15)
    nombre = models.CharField(verbose_name="Nombres", max_length=40)
    apellido = models.CharField(verbose_name="Apellidos", max_length=40)
    direccion = models.TextField(verbose_name="Direccion Habitacional")
    co_movil = models.CharField(max_length=20, choices=cod_movil, null=True, blank=True)
    movil = models.CharField(verbose_name="Número de Celular", max_length=11, null=True, blank=True)
    tlf = models.CharField(verbose_name="Número de Telefonico", max_length=11, null=True, blank=True)
    correo = models.EmailField(verbose_name="Correo Electronico", null=True, blank=True)
    ocupacion = models.CharField('Ocupación Laboral', max_length=100, null=True, blank=True)
    updated = models.DateField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name_plural = "Clientes"
        ordering = ['-pk']

    def __str__(self):
        return (self.cedula)

# MODELO MASCOTA


class Mascota(ModeloBase):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    fnaci = models.DateField(verbose_name='Fecha de Nacimiento')
    sexom = models.CharField(verbose_name='sexo', max_length=40)
    razam = models.CharField(verbose_name='raza', max_length=50)
    peso = models.IntegerField(verbose_name='Peso')
    especie = models.CharField(max_length=50, verbose_name='especie')
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    updated = models.DateField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name_plural = 'Mascotas'
        ordering = ['-id']

    def __str__(self):
        return self.nombre

# MODELO CONSULTA


class Consulta(ModeloBase):
    motivo = models.TextField(verbose_name='Motivo de Consulta')
    sintomas = models.TextField(verbose_name='Sintomas Presentados', null=True, blank=True)
    diapre = models.TextField(verbose_name='Diagnostico Presuntivo', null=True, blank=True)
    diadef = models.TextField(verbose_name='Diagnostico Definitivo', null=True, blank=True)
    temp = models.TextField(verbose_name='Temperatura', null=True, blank=True)
    frecar = models.TextField(verbose_name='Frecuencia Cardiaca', null=True, blank=True)
    freres = models.TextField(verbose_name='Frecuencia Respiratoria', null=True, blank=True)
    examen = models.TextField(verbose_name='Examenes Realizados', null=True, blank=True)
    trata = models.TextField(verbose_name='Tratamientos Aplicados', null=True, blank=True)
    fechac = models.DateTimeField(verbose_name='Fecha de Creacion', auto_now_add=True)
    fechaa = models.DateTimeField(verbose_name='Fecha de Actualizacion', auto_now=True)
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Consultas'
        ordering = ['-fechac']

    def __str__(self):
        return self.motivo

# MODELO DESPARASITACION

class Despa(ModeloBase):
    despa = models.TextField(verbose_name='Desparasitante', null=True, blank=True)
    descripcion = models.TextField(verbose_name='Descripcion', default="", null=True, blank=True)
    fechad = models.DateTimeField(verbose_name='Fecha de Actualizacion', auto_now=True)
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Desparasitaciones'
        ordering = ['fechad']

    def __str__(self):
        return self.despa

# MODELO VACUNA

class Vacuna(ModeloBase):
    nomva = models.TextField(verbose_name='Nombre de la Vacuna/s')
    fechav = models.DateField(verbose_name='Fecha de Actualizacion', auto_now=True)
    dosis = models.TextField(verbose_name='Dosis')
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Vacunaciones'
        ordering = ['fechav']

    def __str__(self):
        return self.nomva

apps/inicio/templates/inicio/DeleteEmpleado.html
<div class="modal-dialog modal-sm modal-dialog-centered">
    <div class="modal-content">
        <form action="{% url 'inicio:del_emp' obj.pk %}" method="POST" role="form" class="form-inline">
            {% csrf_token %}
            <div class="col-14">
                <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-dark text-uppercase mb-1">¿Eliminar a {{ object }} del Sistema?</div>
                        <button type="submit" class="btn verde text-light"><span class="fas fa-trash"></span> Eliminar</button>
                        
                        <a onclick="cerrar_modal()" href="#" class="btn btn-dark text-light"><span class="fa fa-undo"></span> Cancelar</a>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-question-circle fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>  
    </div>
</div>

apps/inicio/templates/inicio/Manten_Cliente.html
{% extends "base/base.html" %}
{% block title %}Mantenimiento a Clientes | Santa Barbara{% endblock %}

{% block contenido %}
    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-verde">Listado de Clientes para Mantenimiento</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not  object_list %}
                <div class="alert alert-info">No hay Clientes Registrados</div> 
            {% else %}
            <table class="table table-striped table-hover" >
                <thead>
                    <th>Cedula</th>
                    <th>Nombre y Apellido</th>
                    <th>Movil</th>
                    <th>Teléfono</th>
                    <th>Correo</th>
                    <th>estado</th>
                    <th class="all">Acciones</th>
                </thead>
                <tbody>
                    {% for item in object_list %}
                    <tr>
                        <td>{{item.tipo}}{{ item.cedula }}</td>
                        <td><a class="nav-link" href="{% url 'regmedic:Cliente_detail' item.pk %}"><h6 class="font-weight-bold text-verde">{{item.nombre}} {{item.apellido}}</h6></a></td>
                        <td>{% if not item.movil %}No Posee {% else %} {{item.co_movil}}{{ item.movil }} {% endif %}</td>
                        <td>{% if not item.tlf %}No Posee{% else %}{{item.co_fijo}}{{ item.tlf }} {% endif %}</td>
                        <td>{% if not item.correo %}No Posee{% else %}{{ item.correo }}{% endif %}</td>
                        <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                        <td>
                            {% if request.user.is_staff %}
                            <a href="{% url 'inicio:man_client_edit' item.pk %}" class="btn btn-warning btn-circle"><i class="fas fa-edit"></i></a>
                            <a onclick="return abrir_modal('{% url 'regmedic:Cliente_delete' item.pk %}')" href="#" class="btn btn-dark text-light btn-circle"><i class="fas fa-trash"></i></a>
                            {% endif %}
                        </td>
                    </tr>  
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block js %}
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
</script>
{% endblock js %}

apps/inicio/templates/inicio/Manten_Cliente_Edit.html
{% extends "base/base.html" %}
{% block title %}Editar Datos| Santa Barbara{% endblock %}
{% block contenido %}
<main role="main">
    <div class="container">
        <div class="row mt-3 mb-3">
            <div class="col-md-9 mx-auto">
                <form action="" method="post" role="form">{% csrf_token %}
                    <div class="cliente_form">
                        <div class="iden">
                            <label for="id_tipo" class="titulo">Identificación</label>
                            <div class="mb-3 tipo">
                                {{form.tipo}}
                                {{form.tipo.errors}}
                            </div>
                            <div class="mb-3 ci">
                                <input type="text" maxlength="8" placeholder="Número de Identificación" id="id_cedula" name="cedula" class="form-control" value="{{obj.cedula}}" autocomplete="off" onkeypress="return justNumbers(event);">
                                {{form.cedula.errors}}
                            </div>
                        </div>
                        <div class="nombres">
                            <div>
                                <label for="id_nombre">Nombres</label>
                                <input type="text" placeholder="Nombres" id="id_nombre" name="nombre" value="{{obj.nombre}}" class="form-control" autocomplete="off" onkeypress="return Solo_Texto(event);">
                                {{form.nombre.errors}}
                            </div>
                            <div>
                                <label for="id_apellido">Apellidos</label>
                                <input type="text" placeholder="Nombres" id="id_apellido" name="apellido" value="{{obj.apellido}}" class="form-control" autocomplete="off" onkeypress="return Solo_Texto(event);">
                                {{form.nombre.errors}}
                            </div>
                        </div>
                        <div class="celular">
                            <label for="id_celular" class="titulo_cel">Celular</label>
                            <div class="form-group">
                                {{form.co_movil}}
                            </div>
                            <div class="">
                                <input type="text" maxlength="7" placeholder="Número" id="id_celular" name="movil" class="form-control" value="{{obj.movil}}" autocomplete="off" onkeypress="return justNumbers(event);">
                                {{form.movil.errors}}
                            </div>
                        </div>
                        <div class="telefono">
                            <label for="id_tlf" class="titulo_tlf">Telefono</label>
                            <div>
                                <input type="text" maxlength="11" placeholder="Número telefonico" id="id_tlf" name="tlf" value="{{obj.tlf}}" class="form-control" autocomplete="off" onkeypress="return justNumbers(event);">
                                {{form.tlf.errors}}
                            </div>
                        </div>
                        <div>
                            <label for="id_correo">Correo</label>
                            <input type="email" name="correo" id="id_correo" value="{{obj.correo}}" placeholder="Correo Electrónico" class="form-control" autocomplete="off">
                            {{form.correo.errors}}
                        </div>
                        <div>
                            <label for="id_ocupacion">Ocupacion</label>
                            {{form.ocupacion}}
                            {{form.ocupacion.errors}}
                        </div>
                        <div class="mt-2 direcc" style="grid-column: 1/3;">
                            <label for="id_direccion">Direccion</label>
                            {{form.direccion}}
                            {{form.direccion.errors}}
                        </div>
                        <div class="form-group mt-3">
                            <div class="custom-control custom-checkbox">
                              <input type="checkbox" class="custom-control-input" id="customCheck1" checked name="estado">
                              <label class="custom-control-label" for="customCheck1">{% if obj.estado == True %}¿Desactivar Cliente? {% else %}¿Activar Cliente? {% endif %} </label>
                            </div>
                        </div>
                    </div> 
                    <div class="text-center mt-5 mb-2">
                        <input type="submit" class="btn verde text-light btn-block" value="Actualizar">
                        <a class="btn btn-block btn-dark text-light" href="{% url 'regmedic:Cliente_list' %}">Cancelar</a>
                    </div> 
                </form>
            </div>
        </div>
    </div>                                   
</main>
{% block js %}
<script type="text/javascript">
	function Solo_Texto(e) {
    var code;
    if (!e) var e = window.event;
    if (e.keyCode) code = e.keyCode;
    else if (e.which) code = e.which;
    var character = String.fromCharCode(code);
    var AllowRegex  = /^[\ba-zA-Z\s-]$/;
    if (AllowRegex.test(character)) return true;     
    return false; 
}
//Solo numeros
function justNumbers(e)
    {
    var keynum = window.event ? window.event.keyCode : e.which;
    if ((keynum == 8) || (keynum == 46))
    return true;
        
    return /\d/.test(String.fromCharCode(keynum));
    }
</script>
{% endblock %}
{% endblock %}

apps/inicio/templates/inicio/Manten_Pets.html
{% extends "base/base.html" %}
{% block title %}Mantenimiento a Mascotas | Santa Barbara{% endblock %}

{% block contenido %}
    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-verde">Listado de Mascotas para Mantenimiento</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not object_list %}
                <div class="alert alert-info">No hay Mascotas Registradas</div> 
            {% else %}
            <table class="table table-striped table-hover" >
                <thead>
                    <th>Cliente</th>
                    <th>Mascota</th>
                    <th>Sexo</th>
                    <th>Especie</th>
                    <th>Raza</th>
                    <th>estado</th>
                    <th class="all">Acciones</th>
                </thead>
                <tbody>
                    {% for item in object_list %}
                    <tr>
                        <td>{{ item.cliente }}</td>
                        <td><a class="nav-link" href="{% url 'regmedic:Mascota_detail' item.pk %}"><h6 class="font-weight-bold text-verde">{{ item.nombre }}</h6></a></td>
                        <td>{{ item.sexom }}</td>
                        <td>{{ item.razam }}</td>
                        <td>{{ item.especie }}</td>
                        <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>

                        <td>
                            {% if request.user.is_staff %}

                            <a href="{% url 'inicio:man_pets_edit' item.pk %}" class="btn btn-warning btn-circle"><i class="fas fa-edit"></i></a>
                            <a onclick="return abrir_modal('{% url 'regmedic:Mascota_delete' item.pk %}')" href="#" class="btn btn-dark text-light btn-circle"><i class="fas fa-trash"></i></a>
                            {% endif %}
                        </td>
                    </tr>  
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block js %}
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
</script>
{% endblock js %}

apps/inicio/templates/inicio/Manten_Pets_Edit.html
{% extends "base/base.html" %}
{% block title %} Editar {{ obj.nombre }} | Santa Barbara{% endblock %}
{% block contenido %}
<main role="main">
        <style>label{text-align: center}</style>
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-9 mx-auto">
                    <div>
                        <br>
                        <h2 class="text-verde text-center">Editar de la Mascota</h2>
                        <br>
                        {% if 'ok' in request.GET %}
                            <p style="color:green;">Se han actualizado correctamente los Datos, <a href="{% url 'regmedic:Mascota_detail' mascota.pk %}">Haz click aqui para ver el resultado</a></p>
                        {% endif %}

                        <form action="" method="POST">{% csrf_token %}
                            <div class="form-producto">
                                <div>
                                    <label for="id_cliente">Propietario de la Mascota</label>
                                    {{form.cliente}}
                                    {{form.cliente.errors}}
                                </div>
                                
                                <div>
                                    <label for="id_nombre">Nombre de la Mascota</label>
                                    <input class="form-control" type="text" value="{{obj.nombre}}" placeholder="nombre de la mascota" name="nombre" id="id_nombre" autocomplete="off" pattern="[A-Za-z]{2,50}">
                                    {{form.nombre.errors}}
                                </div>
                                
                                <div class="mt-3">
                                    <label for="id_fnaci">Fecha de Nacimiento</label>
                                    <input type="text" name="fnaci" id="id_fnaci" value="{{obj.fnaci|date:'SHORT_DATE_FORMAT'}}" class="form-control" readonly >
                                    {{form.fnaci.errors}}
                                </div>
                                
                                <div class="mt-3">
                                    <label for="id_especie">Especie</label>
                                    <select class="custom-select" name="especie" id="id_especie">
                                        <option value="{{obj.especie}}">{{obj.especie}}</option>
                                        {% if not obj.especie == Canino %}
                                        <option value="Canino">Canino</option>
                                        {% else %}
                                        <option value="Felino">Felino</option>
                                        {% endif %}
                                    </select>
                                    {{form.especie.errors}}
                                </div>
                                
                                <div class="mt-3">
                                    <label for="id_razam">Raza</label>
                                    <select class="custom-select" name="razam" id="id_razam">
                                        <option value="{{obj.razam}}">{{obj.razam}}</option>
                                        <option value="">----Raza----</option>
                                        <!--Perrors-->
                                        <optgroup  class="perros">
                                            <!--<option value="">--Caninos--</option>-->
                                            <option value="Pitbull">Pitbull</option>
                                            <option value="Chiguagua">Chiguagua</option>
                                        </optgroup>
                                        <!--Gatos-->
                                        <optgroup class="gatos" >
                                            <!--<option value="">--Feninos--</option>-->
                                            <option value="Peludos">Peludos</option>
                                            <option value="Sin pelos">Sin pelos</option>
                                        </optgroup>
                                    </select>
                                    {{form.razam.errors}}
                                </div>
                                
                                <div class="mt-3">
                                    <label for="id_sexom">Sexo</label>
                                    <select class="custom-select" name="sexom" id="id_sexom">
                                        <option value="{{obj.sexom}}">{{obj.sexom}}</option>
                                        {% if obj.sexom == Hembra %}
                                        <option value="Macho">Macho</option>
                                        {% else %}
                                        <option value="Hembra">Hembra</option>
                                        {% endif %}
                                    </select>
                                    {{form.sexom.errors}}
                                </div>
                                
                                <div class="mt-3">
                                    <label for="id_peso">Peso (Kg)</label>
                                <input class="form-control" type="number" name="peso" value="{{obj.peso}}" id="id_peso" min="0">
                                {{form.peso.errors}}
                                </div>
                                <div class="mt-3">
                                <label for="id_estado">Estado</label>
                                <input class="form-control" type="checkbox" name="estado" id="id_estado" {% if obj.estado == True %} checked {% endif %}>
                                {{form.estado.errors}}
                                </div>
                            
                            </div>
                            <div class="col text-center mt-5">
                                <button type="submit" class="btn verde text-light mr-3"><span class="fas fa-save"></span> Registrar</button>
                                <a href="{% url 'regmedic:Mascota_list' %}" class="btn btn-dark text-light"><span class="fa fa-undo"></span> Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <script>
        const especie = document.getElementById('id_especie');

        const canino = document.querySelector('.perros');
        const fenino = document.querySelector('.gatos');

        especie.addEventListener('click', e => {
            const opcion = especie.options[especie.selectedIndex].value;

            if (opcion == 'Canino') {
                canino.classList.add('activo');
            }else{
                canino.classList.remove('activo');
            }
            if (opcion == 'Felino') {
                fenino.classList.add('activo');
            }else{
                fenino.classList.remove('activo');
            }
        });
    </script>
{% endblock %}
{% block js %}
<script>
    $(function () {
        $("#id_cliente").select2({
            placeholder:"Seleccione el Cliente",
            allowClear:true
        });
        $("#id_fnaci").datetimepicker({
            format: 'Y-m-d',
            timepicker:false,
            yearRange: '-50:+0',
            maxDate: '+0m +0d'
            
        });
    });
    
</script>
{% endblock js %}