ProjecVete/urls.py
from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.inicio.urls', 'inicio'), namespace='inicio')),
    path('regMedic/', include(('apps.regmedic.urls', 'regmedic'), namespace='regmedic')),
    path('accounts/', include('apps.registration.urls')),
    path('reporte/', include(('apps.reporte.urls', 'reporte'), namespace='reporte')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),


    path('accounts/', include('apps.registration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

apps/regmedic/urls.py
from django.urls import path

from .views import ClienteView, ClienteNuevo, ClienteEdit, ClienteInact, ClienteDetail, MascotaView, MascotaNew, MascotaDetail, MascotaEdit, MascotaInact, ConsultaView, ConsultaNew, ConsultaEdit, ConsultaDel, ConsultaDetail, VacunaView, VacunaNew, VacunaEdit, VacunaDel, DespaView, DespaNew, DespaEdit, DespaDel, ClienteDelete, Mascota_Delete

urlpatterns = [
#URLS CLIENTES
    path('Clientes', ClienteView.as_view(), name='Cliente_list'),
    path('Cliente/new', ClienteNuevo.as_view(), name='Cliente_form'),
    path('Cliente/edit/<int:pk>', ClienteEdit.as_view(), name='Cliente_edit'),
    path('Cliente/inac/<int:id>', ClienteInact, name='Cliente_inac'),
    path('Cliente/detail/<int:pk>', ClienteDetail.as_view(), name='Cliente_detail'),
    path('Cliente/<int:pk>/delete', ClienteDelete.as_view(), name='Cliente_delete'),
#URLS MASCOTAS
    path('Mascotas', MascotaView.as_view(), name='Mascota_list'),
    path('Mascota/new', MascotaNew.as_view(), name='Mascota_form'),
    path('Mascota/detail/<int:pk>', MascotaDetail.as_view(), name='Mascota_detail'),
    path('Mascota/edit/<int:pk>', MascotaEdit.as_view(), name='Mascota_edit'),
    path('Mascota/inac/<int:id>', MascotaInact, name='Mascota_inac'),
    path('Mascota/<int:pk>/delete/', Mascota_Delete.as_view(), name='Mascota_delete'),
#URLS CONSULTAS
    path('Consultas', ConsultaView.as_view(), name='Consulta_list'),
    path('Consulta/new', ConsultaNew.as_view(), name='Consulta_form'),
    path('Consulta/edit/<int:pk>', ConsultaEdit.as_view(), name='Consulta_edit'),
    path('Consulta/eliminar/<int:pk>', ConsultaDel.as_view(), name='Consulta_del'),
    path('Consulta/detail/<int:pk>', ConsultaDetail.as_view(), name='Consulta_detail'),
#URLS VACUNACIONES
    path('Vacunas', VacunaView.as_view(), name='Vacuna_list'),
    path('Vacuna/new', VacunaNew.as_view(), name='Vacuna_form'),
    path('Vacuna/edit/<int:pk>', VacunaEdit.as_view(), name='Vacuna_edit'),
    path('Vacuna/eliminar/<int:pk>', VacunaDel.as_view(), name='Vacuna_del'),
#URLS DESPARASITACIONES
    path('Despa', DespaView.as_view(), name='Despa_list'),
    path('Despa/new', DespaNew.as_view(), name='Despa_form'),
    path('Despa/edit/<int:pk>', DespaEdit.as_view(), name='Despa_edit'),
    path('Despa/eliminar/<int:pk>', DespaDel.as_view(), name='Despa_del'),

]

apps/reporte/urls.py
from django.urls import path, re_path
from .reportes import reportmascota_all,\
    reportclient_one, reportmascot_one, reportcliente_all, reportConsulta, reportDespa, reportVacuna
from .views import ReportePersonasPDF


urlpatterns = [
    path('mascotaall/', reportmascota_all, name='mascotaall'),
    path('cliente/one/<int:cedula>', reportclient_one, name='clienteone'),
    path('mascota/one/<int:id>', reportmascot_one, name='mascotaone'),
    path('consulta/<int:id>', reportConsulta, name='consultaDet'),
    path('desparasitacion/<int:id>', reportDespa, name='despaPdf'),
    path('vacunacion/<int:id>', reportVacuna, name='vacunaPdf'),
    path('clienteall/', reportcliente_all, name='clientall'),
    path('allclient/', ReportePersonasPDF.as_view(), name='reportclient')
]

apps/regmedic/models.py
from django.db import models
from datetime import datetime, date, time, timedelta

# Create your models here.

# MODELO CLIENTE
class ModeloBase(models.Model):
    estado = models.BooleanField(default=True)
    estado_notificacion = models.BooleanField(default=True, verbose_name='Estado de Notificación')
    prox_cita = models.DateField(default=date.today, verbose_name='Proxima Visita')
    cont_dias = models.IntegerField(default=3)

    class Meta:
        abstract=True

class Cliente(ModeloBase):
    # Nacionalidad
    nat = "V-"
    juri = "J-"
    ex = "E-"
    tipo_cliente = [(nat, 'V-'), (juri, 'J-'), (ex, 'E-')]

    # Codigo de area Movil
    Digitel1 = "0412"
    Movilnet1 = "0416"
    Movilnet2 = "0426"
    Movistar1 = "0414"
    Movistar2 = "0424"
    cod_movil = [(Digitel1, "0412"), (Movilnet1, "0416"),
                 (Movilnet2, "0426"), (Movistar1, "0414"), (Movistar2, "0424")]

    tipo = models.CharField(max_length=10, choices=tipo_cliente, default=nat)
    cedula = models.CharField(primary_key=True, verbose_name="Número de Cédula", max_length=15)
    nombre = models.CharField(verbose_name="Nombres", max_length=40)
    apellido = models.CharField(verbose_name="Apellidos", max_length=40)
    direccion = models.TextField(verbose_name="Direccion Habitacional")
    co_movil = models.CharField(max_length=20, choices=cod_movil, null=True, blank=True)
    movil = models.CharField(verbose_name="Número de Celular", max_length=11, null=True, blank=True)
    tlf = models.CharField(verbose_name="Número de Telefonico", max_length=11, null=True, blank=True)
    correo = models.EmailField(verbose_name="Correo Electronico", null=True, blank=True)
    ocupacion = models.CharField('Ocupación Laboral', max_length=100, null=True, blank=True)
    updated = models.DateField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name_plural = "Clientes"
        ordering = ['-pk']

    def __str__(self):
        return (self.cedula)

# MODELO MASCOTA


class Mascota(ModeloBase):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    fnaci = models.DateField(verbose_name='Fecha de Nacimiento')
    sexom = models.CharField(verbose_name='sexo', max_length=40)
    razam = models.CharField(verbose_name='raza', max_length=50)
    peso = models.IntegerField(verbose_name='Peso')
    especie = models.CharField(max_length=50, verbose_name='especie')
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    updated = models.DateField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name_plural = 'Mascotas'
        ordering = ['-id']

    def __str__(self):
        return self.nombre

# MODELO CONSULTA


class Consulta(ModeloBase):
    motivo = models.TextField(verbose_name='Motivo de Consulta')
    sintomas = models.TextField(verbose_name='Sintomas Presentados', null=True, blank=True)
    diapre = models.TextField(verbose_name='Diagnostico Presuntivo', null=True, blank=True)
    diadef = models.TextField(verbose_name='Diagnostico Definitivo', null=True, blank=True)
    temp = models.TextField(verbose_name='Temperatura', null=True, blank=True)
    frecar = models.TextField(verbose_name='Frecuencia Cardiaca', null=True, blank=True)
    freres = models.TextField(verbose_name='Frecuencia Respiratoria', null=True, blank=True)
    examen = models.TextField(verbose_name='Examenes Realizados', null=True, blank=True)
    trata = models.TextField(verbose_name='Tratamientos Aplicados', null=True, blank=True)
    fechac = models.DateTimeField(verbose_name='Fecha de Creacion', auto_now_add=True)
    fechaa = models.DateTimeField(verbose_name='Fecha de Actualizacion', auto_now=True)
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Consultas'
        ordering = ['-fechac']

    def __str__(self):
        return self.motivo

# MODELO DESPARASITACION

class Despa(ModeloBase):
    despa = models.TextField(verbose_name='Desparasitante', null=True, blank=True)
    descripcion = models.TextField(verbose_name='Descripcion', default="", null=True, blank=True)
    fechad = models.DateTimeField(verbose_name='Fecha de Actualizacion', auto_now=True)
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Desparasitaciones'
        ordering = ['fechad']

    def __str__(self):
        return self.despa

# MODELO VACUNA

class Vacuna(ModeloBase):
    nomva = models.TextField(verbose_name='Nombre de la Vacuna/s')
    fechav = models.DateField(verbose_name='Fecha de Actualizacion', auto_now=True)
    dosis = models.TextField(verbose_name='Dosis')
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Vacunaciones'
        ordering = ['fechav']

    def __str__(self):
        return self.nomva

apps/regmedic/forms.py
from django import forms
from .models import Cliente, Mascota, Consulta, Vacuna, Despa

# FORMS CLIENTES


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['tipo', 'co_movil', 'cedula', 'nombre', 'apellido',
                  'movil', 'tlf', 'correo', 'ocupacion', 'direccion', 'estado']

        widgets = {
            'tipo': forms.Select(attrs={'class': 'form-control'}),
            'co_movil': forms.Select(attrs={'class': 'form-control'}),
            'cedula': forms.TextInput(attrs={'class': 'form-control ', 'placeholder': 'Cédula', 'maxlength': '8'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control ', 'placeholder': 'Nombres'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control ', 'placeholder': 'Apellidos'}),
            'movil': forms.TextInput(attrs={'class': 'form-control ', 'placeholder': 'Celular', 'maxlength': '11'}),
            'tlf': forms.TextInput(attrs={'class': 'form-control ', 'placeholder': 'Teléfono', 'maxlength': '11'}),
            'correo': forms.EmailInput(attrs={'class': 'form-control ', 'placeholder': 'Correo Electrónico'}),
            'ocupacion': forms.TextInput(attrs={'class': 'form-control ', 'placeholder': 'Ocupación Laboral', 'required': 'True'}),
            'direccion': forms.Textarea(attrs={'class': 'form-control  textarea', 'placeholder': 'Dirección Habitacional', 'required': 'True'}),
        }
# FORMS MASCOTAS


class MascotaForm(forms.ModelForm):
    cliente = forms.ModelChoiceField(
        queryset=Cliente.objects.filter(estado=True).order_by('nombre'))

    class Meta:
        model = Mascota
        fields = ['cliente', 'nombre', 'especie',
                  'razam', 'sexom', 'fnaci', 'peso', 'estado']
        widgets = {
            'cliente': forms.Select(attrs={'class': 'custom-select', 'placeholder': 'Peso de la mascota', 'id': 'id_cliente'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de la mascota'}),
            'fnaci': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Fecha de nacimiento de la mascota'}),
            'especie': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Especie de la mascota'}),
            'razam': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Raza de la mascota'}),
            'sexom': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sexo de la mascota'}),
            'peso': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Peso de la mascota', 'min': 1}),
        }
        labels = {
            'peso': 'Peso (KG)',
            'cliente': 'Propietario de la mascota',
            'nombre': 'Nombre de la Mascota',
            'estado': 'Estado',
            'fnaci': 'Fecha e Nacimiento',
            'especie': 'Especie',
            'razam': 'Raza',
            'sexom': 'Sexo',

        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['cliente'].empty_label = 'Seleccione el cliente'

# FORMS CONSULTAS


class ConsultaForm(forms.ModelForm):
    mascota = forms.ModelChoiceField(
        queryset=Mascota.objects.filter(estado=True).order_by('nombre'))

    class Meta:
        model = Consulta
        fields = ['mascota', 'motivo', 'sintomas', 'temp', 'frecar',
                  'freres', 'diapre', 'examen', 'trata', 'diadef','prox_cita','estado_notificacion']
        widgets = {
            'motivo': forms.Textarea(attrs={'class': 'form-control  textarea', 'placeholder': 'Motivo de la consulta', 'rows': '5'}),
            'sintomas': forms.Textarea(attrs={'class': 'form-control  textarea', 'placeholder': 'Síntomas del paciente', 'rows': '5'}),
            'diapre': forms.Textarea(attrs={'class': 'form-control  textarea', 'placeholder': 'Diagnostico Presuntivo', 'rows': '5'}),
            'temp': forms.Textarea(attrs={'class': 'form-control  textarea', 'placeholder': 'Temperatura del paciente', 'rows': '5'}),
            'frecar': forms.Textarea(attrs={'class': 'form-control  textarea', 'placeholder': 'Frecuencia cardiaca', 'rows': '5'}),
            'freres': forms.Textarea(attrs={'class': 'form-control  textarea', 'placeholder': 'Frecuencia respiratoria', 'rows': '5'}),
            'examen': forms.Textarea(attrs={'class': 'form-control  textarea', 'placeholder': 'Examenes realizados', 'rows': '5'}),
            'diadef': forms.Textarea(attrs={'class': 'form-control  textarea', 'placeholder': 'Diagnostico definitivo', 'rows': '5'}),
            'trata': forms.Textarea(attrs={'class': 'form-control  textarea', 'placeholder': 'Tratamientos aplicados', 'rows': '5'}),
            'mascota': forms.Select(attrs={'class': 'form-control select2', 'required': 'True'}),
            'prox_cita': forms.DateInput(attrs={'class': 'form-control', 'required': 'False','readonly':'True'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['mascota'].empty_label = 'Seleccione la mascota'

# FORMS VACUNACIONES


class VacunaForm(forms.ModelForm):
    mascota = forms.ModelChoiceField(
        queryset=Mascota.objects.filter(estado=True).order_by('nombre'))

    class Meta:
        model = Vacuna
        fields = ['mascota', 'nomva', 'dosis','prox_cita','estado_notificacion']
        widgets = {
            'mascota': forms.Select(attrs={'class': 'custom-select selectM'}),
            'nomva': forms.TextInput(attrs={'class': 'form-control ', 'placeholder': 'Nombre de la Vacuna'}),
            'dosis': forms.TextInput(attrs={'class': 'form-control ', 'placeholder': 'Dosis de la Vacuna'}),
            'prox_cita': forms.DateInput(attrs={'class': 'form-control', 'required': 'False','readonly':'True'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['mascota'].empty_label = 'Seleccione la mascota'

# FORMS DESPARASITACIONES


class DespaForm(forms.ModelForm):
    mascota = forms.ModelChoiceField(
        queryset=Mascota.objects.filter(estado=True).order_by('nombre'))

    class Meta:
        model = Despa
        fields = ['mascota', 'despa', 'descripcion','prox_cita','estado_notificacion']

        widgets = {
            'mascota': forms.Select(attrs={'class': 'custom-select'}),
            'despa': forms.TextInput(attrs={'class': 'form-control textarea', 'placeholder': 'Desparasitante'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control textarea', 'placeholder': 'Descripcion de la Desparacitación', 'rows': '5'}),
            'prox_cita': forms.DateInput(attrs={'class': 'form-control', 'required': 'False','readonly':'True'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['mascota'].empty_label = 'Seleccione la mascota'

apps/regmedic/templates/regmedic/Mascota_detail.html
{% extends "base/base.html" %}
{% block title %}{{ obj.nombre }} | Santa Barbara{% endblock %}

{% block contenido %}

<main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-10 mx-auto">
                    <h1 class="text-center mb-4 colorA text-verde">Detalles de la Mascota</h1>
                    <h2 class="section-heading mt-4 mb-4 text-capitalize">
    
                    {{obj.nombre}}

                        <a href="{% url 'regmedic:Mascota_edit' obj.id %}"><span class="ml-3 h3 text-warning fa fa-edit"></span></a> 
                        <a onclick="return abrir_modal('{% url 'regmedic:Mascota_inac' obj.id %}')" href=""><span class="ml-3 h3 text-dark "><i class="fa fa-power-off"></i></span></a> 
                        <a href="{% url 'reporte:mascotaone' obj.pk  %}" target="_blank"><span class="ml-2 h3 text-dark fas fa-file-pdf"></span></a> 

                    </h2>
                    <p class="h5 mb-3">
                        <span class="text-verde fa fa-calendar-times icon"> Fecha de Nacimiento</span> <span id="fnaci" class="h4">{{obj.fnaci|date:"d/m/Y"}}</span> 
                    </p>
                    <p class="h5 mb-3">
                        <span class="text-verde fas fa-birthday-cake icon"> Edad</span> <span id="edad" class="h4"></span> <span class="anos h4"></span>
                    </p>
                    <p class="h5 mb-3">
                        <span class="text-verde fas fa-paw icon"> Especie</span> <span class="h4">{{obj.especie}}</span> 
                    </p>
                    <p class="h5 mb-3">
                        <span class="text-verde fas fa-book icon"> Raza</span> <span class="h4">{{obj.razam}}</span>
                    </p>
                    <p class="h5 mb-3"> 
                        <span class="text-verde fa fa-venus-mars icon"> Sexo</span> <span class="h4">{{obj.sexom}}</span>
                    </p>
                    <p class="h5 mb-3">
                        <span class="text-verde fa fa-balance-scale icon"> Peso</span> <span class="h4">{{obj.peso}}</span> <span>Kg</span>
                    </p>
                    <div class="h5 mb-3">
                        <span class="text-verde fa fa-user icon"> Propietario </span> <a class="card-link text-verde" href="{% url 'regmedic:Cliente_detail' obj.cliente.pk %}">{{obj.cliente}}</a>
                    <div class="mt-5">
                        <h2 class=" text-center text-verde"><span class="icon fas fa-file-medical"></span> Historia Médica</h2>
                        <br>
                        <h3 class="fa fa-briefcase-medical text-dark mb-4"> 
                        Consultas 
                            <a href="{% url 'regmedic:Consulta_form' %}"><span class="fa fa-plus icon ml-3 text-verde"></span></a>
                        
                        </h3>
                        <div class="card shadow mb-4">
                            <div class="card-body">
                                {% if objc %}
                                <table class="table table-striped table-hover" >
                                    <thead>
                                        <th>Id</th>
                                        <th>Motivo</th>
                                        <th>Tratamientos</th>
                                        <th>Fecha Modificación</th>
                                        <th class="all">Acciones</th>
                                    </thead>
                                    <tbody>
                                        {% for item in objc %}
                                        <tr>
                                            <td>{{ item.id }}</td>
                                            <td><a class="nav-link" href="{% url 'regmedic:Consulta_detail' item.pk %}"><h6 class="font-weight-bold text-verde">{{ item.motivo }}</h6></a></td>
                                            <td>{{ item.trata }}</td>
                                            <td>{{ item.fechaa|date:"SHORT_DATE_FORMAT" }}</td>
                                            <td>
                                                <a href="{% url 'regmedic:Consulta_edit' item.pk %}" class="btn btn-warning btn-circle"><i class="fas fa-edit"></i></a>
                                                <a onclick="return abrir_modal('{% url 'regmedic:Consulta_del' item.pk %}')" href="#" class="btn btn-dark btn-circle"><i class="fas fa-trash"></i></a>
                                                <a href="{% url 'reporte:consultaDet' item.id  %}" target="_blank"><span class="h3 text-light fas fa-file-pdf btn-circle verde"></span></a>
                                                                                                
                                            </td>
                                        </tr>  
                                        {% endfor %}
                                    </tbody>
                                </table>
                                {% else %}
                                    <p class="mt-3 mb-3"><span class="alert alert-dismissible alert-dark text-dark"> No tiene consulta registrada</span></p>
                                {% endif %}
                            </div>
                        </div>
                        <h2 class="text-center text-verde mt-5"><span class="icon fas fa-file-medical"></span> Plan Sanitario</h2>
                        <h3 class="fas fa-syringe text-dark mt-4 mb-4"> Vacunaciones
                            <a href="{% url 'regmedic:Vacuna_form' %}"><span class="fa fa-plus icon ml-3 text-verde"></span></span></a>
                        </h3>

                        <div class="card shadow mb-4">
                            <div class="card-body">
                            <!--Vacuna-->
                            {% if objv %}
                            <table class="table table-striped table-hover" >
                                <thead>
                                    <th>Id</th>
                                    <th>Vacuna</th>
                                    <th>Dosis</th>
                                    <th>Fecha de la Vacunación</th>
                                    <th class="all">Acciones</th>
                                </thead>
                                <tbody>
                                    {% for item2 in objv %}
                                    <tr>
                                        <td>{{ item2.id }}</td>
                                        <td>{{ item2.nomva }}</td>
                                        <td>{{ item2.dosis }}</td>
                                        <td>{{ item2.fechav|date:"SHORT_DATE_FORMAT" }}</td>
                                        <td>
                                            <a href="{% url 'regmedic:Vacuna_edit' item2.pk %}" class="btn btn-warning btn-circle"><i class="fas fa-edit"></i></a>
                                            <a onclick="return abrir_modal('{% url 'regmedic:Vacuna_del' item2.pk %}')" href="#" class="btn btn-dark text-light btn-circle"><i class="fas fa-trash"></i></a>
                                        </td>
                                    </tr>  
                                    {% endfor %}
                                </tbody>
                            </table>
                            {% else %}
                                <p class="mt-3 mb-3"><span class="alert alert-dismissible alert-dark text-dark"> No tiene Vacunaciones registrada</span></p>
                            {% endif %}
                            </div>
                        </div>
                        <!--Desparacitación-->
                        <h3 class="fas fa-bug text-dark mt-4 mb-4"> Desparasitaciones
                            <a href="{% url 'regmedic:Despa_form' %}"><span class="icon fas fa-plus icon ml-3 text-verde"></span></span></a>
                        </h3>

                        <div class="card shadow mb-4">
                            <div class="card-body">
                            {% if objd %}
                            <table class="table table-striped table-hover" >
                                <thead>
                                    <th>Id</th>
                                    <th>Desparasitante</th>
                                    <th>Descripción</th>
                                    <th>Fecha de la Desparasitación</th>
                                    <th class="all">Acciones</th>
                                </thead>
                                <tbody>
                                    {% for item3 in objd %}
                                    <tr>
                                        <td>{{ item3.id }}</td>
                                        <td>{{ item3.despa }}</td>
                                        <td>{{ item3.descripcion }}</td>
                                        <td>{{ item3.fechad|date:"SHORT_DATE_FORMAT" }}</td>
                                        <td>
                                            <a href="{% url 'regmedic:Despa_edit' item3.pk %}" class="btn btn-warning btn-circle"><i class="fas fa-edit"></i></a>
                                            <a onclick="return abrir_modal('{% url 'regmedic:Despa_del' item3.pk %}')" href="#" class="btn btn-dark text-light btn-circle"><i class="fas fa-trash"></i></a>
                                        </td>
                                    </tr>  
                                    {% endfor %}
                                </tbody>
                            </table>
                            {% else %}
                                <p class="mt-3"><span class="alert alert-dismissible alert-dark text-dark"> No tiene Desparacitaciones registrada</span></p>
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock contenido %}
{% block js %}
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
function calculateAge(birthday) {
    var birthday_arr = birthday.split("/");
    var birthday_date = new Date(birthday_arr[2], birthday_arr[1] - 1, birthday_arr[0]);
    var ageDifMs = Date.now() - birthday_date.getTime();
    var ageDate = new Date(ageDifMs);
    return Math.abs(ageDate.getUTCFullYear() - 1970);
}

var age = calculateAge("{{obj.fnaci|date:"SHORT_DATE_FORMAT"}}");
document.querySelector("#edad").textContent = calculateAge("{{obj.fnaci|date:"SHORT_DATE_FORMAT"}}");

if (age == 1) {
    document.querySelector(".anos").innerHTML="año"
}else{
    document.querySelector(".anos").innerHTML="años"
}
if (age == 0){
    document.querySelector(".anos").innerHTML="Aún no cumple su primer año"
    document.querySelector("#edad").innerHTML=""
}
</script>
{% endblock js %}